function Stratvis
clear all;
close all;
clc;

scrn_size = get(0, 'ScreenSize');

f = figure('Name', 'StratVis', ...
    'Visible', 'on', ...
    'Position', [0,0,1366,768], ...
    'NumberTitle', 'Off', ...
    'MenuBar', 'none', ...
    'resize', 'off'...
    );
participant = uicontrol( ...
    'Parent', f, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', 'Participant :', ...
    'Position', [100, 430, 105, 15]...
    );
participant_edit = uicontrol( ...
    'Parent', f, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', '', ...
    'Position', [190, 430, 105, 15]...
    );
%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------Panel de chargement----------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------

chargement = uipanel( ...
    'Parent', f, ...
    'Title', 'Chargement des données', ...
    'Units', 'Pixels', ...
    'FontSize', 10, ...
    'Position', [50, 520, 400, 200 ] ...
    );

load_button1 = uicontrol('Parent', chargement, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Coordonnées Marqueur', ...
    'Tag','Load_button1',...
    'Position', [20, 130, 200, 30], ...
    'callback', {@load1_callback}...
    );

load_button2 = uicontrol('Parent', chargement, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Coordonnées Masques', ...
    'Tag','Load_button2',...
    'Position', [20, 90, 200, 30], ...
    'callback', {@load2_callback}...
    );
 set(load_button2, 'Enable', 'off');

load_button3 = uicontrol('Parent', chargement, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Vidéo', ...
    'Tag','Load_button3',...
    'Position', [20, 50, 200, 30],...
    'callback', {@load3_callback}...
    );
 %set(load_button3, 'Enable', 'off');

validation_button = uicontrol('Parent', chargement, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Valider', ...
    'Position', [250, 90, 120, 30], ...
    'callback', {@validation_callback}...
    );


%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------PanelVidéo-------------------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------
v = uipanel( ...
    'Parent', f, ...
    'Title', 'Chargement des données', ...
    'Units', 'Pixels', ...
    'FontSize', 10, ...
    'Position', [500, 400, 800, 320 ] ...
    );

handles.movie_scrn = axes( ...
    'Parent', v, ...
    'tag', 'movie_scrn', ...
    'Units', 'Pixels', ...
    'YTick', [], ...
    'XTick', [], ...
    'NextPlot', 'add', ...
    'Position', [20, 10, 380, 340] ...
    );
%set(handles.movie_scrn, 'Visible', 'off');

movie_slider = uicontrol( ...
    'Parent', v, ...
    'Style', 'slider', ...
    'String', 'test', ...
    'Position', [450, 20, 220, 20], ...
    'Callback', {@movieslider_callback}...
    );
 set(movie_slider, 'min',1);
  set(movie_slider, 'max',100); 
  set(movie_slider, 'value',2); 
addlistener(movie_slider, 'ContinuousValueChange', @movieslider_callback);

handles.play_button = uicontrol( ...
    'Parent', v, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Play', ...
    'Tag','play_button',...
    'Position', [450, 180, 60, 25],...
    'callback', {@play_Callback} ...
    );
handles.stop_button = uicontrol( ...
    'Parent', v, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Pause', ...
    'Position', [520, 180, 60, 25],...
    'callback', {@stop_Callback} ...
    );
uicontrol( ...
    'Parent', v, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', 'Debut (sec) :', ...
    'Position', [450, 110, 105, 15], ...
    'callback', {@stop_Callback} ...
    );

starttimemap_edit = uicontrol( ...
    'Parent', v, ...
    'Style', 'edit', ...
    'FontSize', 10, ...
    'Value', 0, ...
    'Position', [580, 110, 60, 20],...
    'Callback', {@time_edit_callback}...
    );
uicontrol( ...
    'Parent', v, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', 'Temps actuel (sec) :', ...
    'Position', [450, 140, 105, 15], ...
    'callback', {@stop_Callback} ...
    );

Currenttime_edit = uicontrol( ...
    'Parent', v, ...
    'Style', 'edit', ...
    'FontSize', 10, ...
    'Value', 0, ...
    'Position', [580, 140, 60, 20]...
    );
% endtimemap_text =
uicontrol( ...
    'Parent', v, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', 'Fin (sec) :', ...
    'Position', [450, 80, 105, 15] ...
    );

endtimemap_edit = uicontrol( ...
    'Parent', v, ...
    'Style', 'edit', ...
    'FontSize', 10, ...
    'Position', [580, 80, 60, 20],...
    'Callback', {@endtime_callback}...
    );
%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------Tableau--------------------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------
tab = uitable(...
    'Parent',f,...
    'Data',randi(100,10,3),...
    'Position',[50 20 1250 350]...
    );
tab.ColumnName = {'ROI','Temps de fixation','Temps total','Ordre de decouverte'};
tab.ColumnEditable = true;
set(tab,'ColumnWidth',{304});

%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------Variables--------------------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------
handles.filename3='';
handles.mem=1;
handles.endtime=2000;
handles.depart=1;
%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------Callbacks--------------------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------

    function load1_callback (hObject,~)
        set(load_button2, 'Enable', 'on');
        [FileName,PathName,FilterIndex] = uigetfile('*.txt', 'Selectionner le fichier texte avec les coordonnées du marqueur');
        disp(hObject.String)
        handles = guihandles(hObject);
        handles.Load_button1.String = FileName;
        handles.marqueur = importdata(FileName);
        handles.filename1=FileName;
        guidata(hObject, handles);
    end
    function load2_callback (hObject,~)
        set(load_button3, 'Enable', 'on');
        [FileName,PathName,~] = uigetfile('*.txt', 'Selectionner le fichier texte avec les coordonnées des masques');
        disp(hObject.String)
        handles = guihandles(hObject);
        handles.Load_button2.String = FileName;
        handles.masque = importdata(FileName);
        handles.filename2=FileName;
        guidata(hObject, handles);
    end
    function load3_callback (hObject,eventdatta,handles)
        %recuperation nom/chemin ... du fichier recherché
        [FileName,PathName,FilterIndex] = uigetfile('*.mp4', 'Selectionner la vidéo');
        %initialisation handles
        handles = guihandles(hObject);
        %def
        handles.mem=1;
        handles.filename3=FileName
        currAxes = handles.movie_scrn;
        handles.Load_button3.String = FileName;
        %%sauvegarde des handles
        %guidata(hObject, handles)
        %affichage 1ere frame
        obj = VideoReader(FileName);
%         i=1;
%         while hasFrame(obj)
%             this_frame{i} = readFrame(obj);
%             i=i+1
%         end
            
        this_frame = read(obj, handles.mem);
        %rotations image
        this_frame=imrotate(this_frame,180);
        this_frame = flip(this_frame ,2);
        %affichage sur l'axe
       image(this_frame, 'Parent', currAxes);
       handles.endtime =ceil(obj.FrameRate*obj.Duration);
        set(movie_slider, 'min',1,'max',handles.endtime);
        set(starttimemap_edit,'String',0);
        set(endtimemap_edit,'String',handles.endtime/30);
        set(participant_edit,'String',handles.filename3);
        guidata(hObject,handles)
    end
    function play_Callback(~,~)
        %initialisation 
        handles=guidata(handles.play_button)
        currAxes = handles.movie_scrn;
        obj = VideoReader(handles.filename3);
        handles.play_button.Value =1;
        handles.depart=handles.mem;
        set(starttimemap_edit,'String',num2str(round(handles.depart/30,2)));
        %boucle d'affichage des frames
        for k= handles.depart:handles.endtime 
            %condition d'arret
            if handles.play_button.Value ==1
                set(endtimemap_edit,'String','');
                this_frame = read(obj,k);
                this_frame=imrotate(this_frame,180);
                this_frame = flip(this_frame ,2);
                cla;
                image(this_frame, 'Parent', currAxes);
                handles.mem = k;
                set(movie_slider, 'Value',k);
                set(Currenttime_edit,'String',num2str(round(k*(1/30),0)));
                pause(1/60)
            end               
            guidata(handles.play_button,handles)
        end
    end

    function stop_Callback(~,~)
        handles=guidata(handles.play_button);
        set(handles.play_button, 'Enable', 'on');
        handles.play_button.Value = 0;
         set(endtimemap_edit, 'String', handles.mem/30);
        
    end

    function validation_callback(hObject,~)
    end
    function time_edit_callback(source, ~)
        handles=guidata(handles.play_button);
        handles.mem=str2double(get(source,'String'))*30
        currAxes = handles.movie_scrn;
        obj = VideoReader(handles.filename3);
        this_frame = read(obj,handles.mem);
        this_frame=imrotate(this_frame,180);
        this_frame = flip(this_frame ,2);
        image(this_frame, 'Parent', currAxes);
        currAxes.Visible = 'off' ;
        guidata(handles.play_button,handles)
    end
    function movieslider_callback(source, ~)
         set(endtimemap_edit,'String','');
         set(starttimemap_edit,'String','');
         
         val = get(source, 'Value');
         handles=guidata(handles.play_button)
         currAxes = handles.movie_scrn;
         obj = VideoReader(handles.filename3);
         handles.endtime =ceil(obj.FrameRate*obj.Duration);
         set(movie_slider, 'max',handles.endtime); 
         i = round(val)
        set(currAxes, 'NextPlot', 'add', 'YTick', [], 'XTick', []);
        this_frame=read(obj,i);
        this_frame=imrotate(this_frame,180);
        this_frame = flip(this_frame ,2);
        image(this_frame, 'Parent', currAxes);        
        axis off;
        
        set(Currenttime_edit,'String',i/30);
        handles.mem=i;
        guidata(handles.play_button,handles)
        
    end
    function endtime_callback(source,~)
        handles=guidata(handles.play_button);
        handles.endtime=str2double(get(source,'String'))*30
        guidata(handles.play_button,handles)
    end
end