clear all;
close all;
clc

scrn_size = get(0, 'ScreenSize');

f = figure('Name', 'StratVis', ...
    'Visible', 'on', ...
    'Position', [0,0,scrn_size(3),scrn_size(4)], ...
    'NumberTitle', 'Off', ...
    'MenuBar', 'none', ...
    'resize', 'off'...
    );

%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------Panel de chargement----------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------

chargement = uipanel( ...
    'Parent', f, ...
    'Title', 'Chargement des données', ...
    'Units', 'Pixels', ...
    'FontSize', 10, ...
    'Position', [10, 520, 400, 200 ] ...
    );

load_button1 = uicontrol('Parent', chargement, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Coordonnées Marqueur', ...
    'Tag','Load_button1',...
    'Position', [20, 130, 200, 30], ...
    'callback', {@load1_callback}...   
);

load_button2 = uicontrol('Parent', chargement, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Coordonnées Masques', ...
     'Tag','Load_button2',...
    'Position', [20, 90, 200, 30], ...
    'callback', {@load2_callback}...   
);

load_button3 = uicontrol('Parent', chargement, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Vidéo', ...
     'Tag','Load_button3',...
    'Position', [20, 50, 200, 30],...
     'callback', {@load3_callback}...  
);

validation_button = uicontrol('Parent', chargement, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Valider', ...
    'Position', [250, 90, 120, 30], ...
    'callback', {@validation_callback}...  
);


%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------PanelVidéo-------------------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------
v = uipanel( ...
    'Parent', f, ...
    'Title', 'Chargement des données', ...
    'Units', 'Pixels', ...
    'FontSize', 10, ...
    'Position', [500, 400, 700, 320 ] ...
    );

handles.movie_scrn_1 = axes( ...
    'Parent', v, ...
    'tag', 'movie_scrn', ...
    'Units', 'Pixels', ...
    'YTick', [], ...
    'XTick', [], ...
    'NextPlot', 'add', ...
    'Position', [20, 10, 350, 350] ...
    );

movie_slider = uicontrol( ...
    'Parent', v, ...
    'Style', 'slider', ...
    'String', 'test', ...
    'Position', [400, 20, 220, 20], ...
    'SliderStep', [.001, .01]...
    );

play_stop_button = uicontrol( ...
    'Parent', v, ...
    'Style', 'pushbutton', ...
    'FontSize', 10, ...
    'String', 'Play', ...
    'Position', [400, 180, 60, 25]...
    );

uicontrol( ...
    'Parent', v, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', 'Debut (sec) :', ...
    'Position', [400, 110, 105, 15] ...
    );

starttimemap_edit = uicontrol( ...
    'Parent', v, ...
    'Style', 'edit', ...
    'FontSize', 10, ...
    'Position', [530, 110, 60, 20]...
    );

% endtimemap_text =
uicontrol( ...
    'Parent', v, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', 'Fin (sec) :', ...
    'Position', [400, 80, 105, 15] ...
    );

endtimemap_edit = uicontrol( ...
    'Parent', v, ...
    'Style', 'edit', ...
    'FontSize', 10, ...
    'Position', [530, 80, 60, 20]...
    );

%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------Variables--------------------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------
masque=0;
marqueur=0;
video=0;
Filename3='';

%---------------------------------------------------------------------------------------------------------------------
%----------------------------------------------Callbacks--------------------------------------------------------------
%---------------------------------------------------------------------------------------------------------------------

function load1_callback (hObject,~)
[FileName,PathName,FilterIndex] = uigetfile('*.txt', 'Selectionner le fichier texte avec les coordonnées du marqueur');
disp(hObject.String)
handles = guihandles(hObject);
handles.Load_button1.String = FileName;
marqueur = importdata(FileName);
end

function load2_callback (hObject,~)
[FileName,PathName,FilterIndex] = uigetfile('*.txt', 'Selectionner le fichier texte avec les coordonnées des masques');
disp(hObject.String)
handles = guihandles(hObject);
handles.Load_button2.String = FileName;
masque = importdata(FileName);
end

function load3_callback (hObject,~)
[FileName,PathName,FilterIndex] = uigetfile('*.avi', 'Selectionner la vidéo')
disp(hObject.String)
handles = guihandles(hObject);
handles.Load_button3.String = FileName;

% videoFReader   = vision.VideoFileReader(FileName);
% depVideoPlayer = vision.DeployableVideoPlayer;
% cont = ~isDone(videoFReader);
%   while cont
%     frame = step(videoFReader);
%     step(depVideoPlayer, frame);   
%     cont = ~isDone(videoFReader) && isOpen(depVideoPlayer);
%   end
%  release(videoFReader);
% release(depVideoPlayer);
obj = VideoReader(FileName);
ax = handles.movie_scrn;
    while hasFrame(obj)
        vidFrame = readFrame(obj);
        image(vidFrame, 'Parent', ax);
        set(ax, 'Visible', 'off');       
    end
    clear obj
end

function validation_callback(hObject,~)
end

